import { Player, Session, Match, LeaderboardEntry, Badge } from "./types"

export const badges: Badge[] = [
  { id: "1", name: "Premier Match", icon: "🎾", description: "A joué son premier match" },
  { id: "2", name: "Série de 5", icon: "🔥", description: "5 victoires consécutives" },
  { id: "3", name: "Social", icon: "🤝", description: "A joué avec 10 partenaires différents" },
  { id: "4", name: "Régulier", icon: "📅", description: "Joue chaque semaine depuis 1 mois" },
  { id: "5", name: "Top 10", icon: "🏆", description: "A atteint le top 10 du classement" },
  { id: "6", name: "Centurion", icon: "💯", description: "100 matchs joués" },
  { id: "7", name: "Hôte", icon: "⭐", description: "A organisé 20 sessions" },
  { id: "8", name: "Challenger", icon: "⚡", description: "A battu un joueur mieux classé" },
]

export const players: Player[] = [
  {
    id: "1",
    name: "Lucas Martin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lucas",
    level: "avancé",
    city: "Paris",
    wins: 47,
    losses: 12,
    rank: 1,
    xp: 4850,
    badges: [badges[0], badges[1], badges[4], badges[7]],
    joinDate: "2024-01-15",
  },
  {
    id: "2",
    name: "Emma Dubois",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
    level: "pro",
    city: "Lyon",
    wins: 52,
    losses: 8,
    rank: 2,
    xp: 4720,
    badges: [badges[0], badges[1], badges[2], badges[4], badges[5]],
    joinDate: "2023-11-20",
  },
  {
    id: "3",
    name: "Thomas Petit",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=thomas",
    level: "avancé",
    city: "Bordeaux",
    wins: 38,
    losses: 15,
    rank: 3,
    xp: 4200,
    badges: [badges[0], badges[2], badges[3]],
    joinDate: "2024-02-01",
  },
  {
    id: "4",
    name: "Léa Bernard",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lea",
    level: "intermédiaire",
    city: "Marseille",
    wins: 29,
    losses: 18,
    rank: 4,
    xp: 3650,
    badges: [badges[0], badges[6]],
    joinDate: "2024-03-10",
  },
  {
    id: "5",
    name: "Hugo Moreau",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=hugo",
    level: "intermédiaire",
    city: "Paris",
    wins: 25,
    losses: 20,
    rank: 5,
    xp: 3100,
    badges: [badges[0], badges[3]],
    joinDate: "2024-04-05",
  },
  {
    id: "6",
    name: "Chloé Leroy",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chloe",
    level: "avancé",
    city: "Toulouse",
    wins: 33,
    losses: 14,
    rank: 6,
    xp: 3800,
    badges: [badges[0], badges[1], badges[7]],
    joinDate: "2024-01-28",
  },
  {
    id: "7",
    name: "Antoine Roux",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=antoine",
    level: "débutant",
    city: "Nice",
    wins: 8,
    losses: 12,
    rank: 15,
    xp: 980,
    badges: [badges[0]],
    joinDate: "2024-06-01",
  },
  {
    id: "8",
    name: "Julie Girard",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=julie",
    level: "intermédiaire",
    city: "Nantes",
    wins: 22,
    losses: 16,
    rank: 8,
    xp: 2750,
    badges: [badges[0], badges[2]],
    joinDate: "2024-02-20",
  },
]

export const sessions: Session[] = [
  {
    id: "1",
    host: players[0],
    club: "Padel Club Paris 15",
    city: "Paris",
    date: "2026-02-28",
    time: "19:00",
    duration: "1h30",
    level: "avancé",
    spotsTotal: 4,
    spotsTaken: 2,
    players: [players[0], players[4]],
    status: "open",
    price: 12,
    description: "Session entre joueurs motivés, ambiance cool mais on joue pour gagner !",
  },
  {
    id: "2",
    host: players[1],
    club: "Lyon Padel Indoor",
    city: "Lyon",
    date: "2026-02-28",
    time: "18:00",
    duration: "2h",
    level: "pro",
    spotsTotal: 4,
    spotsTaken: 3,
    players: [players[1], players[2], players[5]],
    status: "open",
    price: 15,
    description: "Recherche un 4ème joueur de bon niveau pour compléter l'équipe.",
  },
  {
    id: "3",
    host: players[3],
    club: "Marseille Beach Padel",
    city: "Marseille",
    date: "2026-03-01",
    time: "10:00",
    duration: "1h30",
    level: "tous niveaux",
    spotsTotal: 4,
    spotsTaken: 1,
    players: [players[3]],
    status: "open",
    description: "Session détente le samedi matin, tous niveaux bienvenus !",
  },
  {
    id: "4",
    host: players[6],
    club: "Nice Padel Center",
    city: "Nice",
    date: "2026-03-01",
    time: "14:00",
    duration: "1h30",
    level: "débutant",
    spotsTotal: 4,
    spotsTaken: 2,
    players: [players[6], players[7]],
    status: "open",
    price: 10,
    description: "Session débutants pour progresser ensemble dans la bonne humeur.",
  },
  {
    id: "5",
    host: players[2],
    club: "Bordeaux Padel Arena",
    city: "Bordeaux",
    date: "2026-03-02",
    time: "17:30",
    duration: "2h",
    level: "intermédiaire",
    spotsTotal: 4,
    spotsTaken: 4,
    players: [players[2], players[3], players[4], players[7]],
    status: "full",
    price: 11,
    description: "Session complète, on vous attend !",
  },
]

export const matches: Match[] = [
  {
    id: "1",
    date: "2026-02-25",
    players: {
      team1: [players[0], players[4]],
      team2: [players[2], players[5]],
    },
    score: {
      team1: [6, 7, 6],
      team2: [4, 5, 3],
    },
    winner: "team1",
    club: "Padel Club Paris 15",
    city: "Paris",
  },
  {
    id: "2",
    date: "2026-02-24",
    players: {
      team1: [players[1], players[3]],
      team2: [players[6], players[7]],
    },
    score: {
      team1: [6, 6],
      team2: [2, 3],
    },
    winner: "team1",
    club: "Lyon Padel Indoor",
    city: "Lyon",
  },
  {
    id: "3",
    date: "2026-02-23",
    players: {
      team1: [players[2], players[4]],
      team2: [players[0], players[1]],
    },
    score: {
      team1: [4, 6, 5],
      team2: [6, 4, 7],
    },
    winner: "team2",
    club: "Bordeaux Padel Arena",
    city: "Bordeaux",
  },
]

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, player: players[0], points: 4850, change: "same" },
  { rank: 2, player: players[1], points: 4720, change: "up", changeAmount: 1 },
  { rank: 3, player: players[2], points: 4200, change: "down", changeAmount: 1 },
  { rank: 4, player: players[5], points: 3800, change: "up", changeAmount: 2 },
  { rank: 5, player: players[3], points: 3650, change: "same" },
  { rank: 6, player: players[4], points: 3100, change: "down", changeAmount: 2 },
  { rank: 7, player: players[7], points: 2750, change: "up", changeAmount: 1 },
  { rank: 8, player: players[6], points: 980, change: "same" },
]

export const currentUser = players[4] // Hugo Moreau - notre utilisateur fictif
